name: terraform workflow

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        name: terraform actions
        runs-on: ubuntu-latest

        steps:
          - name: checkout code
            uses: actions/checkout@v4

          -  name: installing terraform
             uses: hashicorp/setup-terraform@v2
             with:
              terraform_version: 1.10.5

          - name: intializing terraform
            working-directory: dev-infra
            run: terraform init

          - name: terraform formatting
            working-directory: dev-infra
            run: terraform fmt -recursive -check
            
          - name: validating terraform
            working-directory: dev-infra
            run: terraform validate