name: Terraform Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-test:
    name: Terraform Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Initializing Terraform
        working-directory: dev-infra
        run: terraform init

      - name: Terraform Formatting
        working-directory: dev-infra
        run: terraform fmt -recursive -check

      - name: Validating Terraform
        working-directory: dev-infra
        run: terraform validate