name: terraform workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: terraform-actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Initialize Terraform
        working-directory: dev-infra
        run: terraform init

      - name: Check Terraform formatting
        working-directory: dev-infra
        run: terraform fmt -recursive -check

      - name: Validate Terraform configuration
        working-directory: dev-infra
        run: terraform validate